// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uppfxuaiqkxuhnafjkdq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVwcGZ4dWFpcWt4dWhuYWZqa2RxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDk5OTAsImV4cCI6MjA3MjIyNTk5MH0.eJA1_H86GBp9V7xK7eaRv6VFH4YXdbbdfCZ27sipMPI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});